# -*- coding: utf-8 -*-
"""Data_Cleaning_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8-_wFAUQ89lukaqGGbnvSIQXPj2v_7P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')

df.head()

df.isnull().sum()

df = df.drop_duplicates()
df.shape

sns.boxplot(x=df['fare'])
plt.title("Outlier Detection - Fare")
plt.show()

plt.hist(df['age'])

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")

plt.show()

plt.scatter(df['age'], df['fare'])

plt.title("Age vs Fare")
plt.xlabel("Age")
plt.ylabel("Fare")

plt.show()

df['class'].value_counts().plot(kind='bar')

plt.title("Passenger Class Count")
plt.xlabel("Class")
plt.ylabel("Count")

plt.show()

sns.heatmap(df.corr(numeric_only=True),
            annot=True)

plt.title("Correlation Heatmap")

plt.show()

df.to_csv("cleaned_titanic.csv", index=False)